# Generated by Django 5.0.14 on 2025-10-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(default='Primary Instance', help_text='Friendly name for this WhatsApp instance', max_length=100)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('qr_pending', 'QR Code Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('auth_failed', 'Authentication Failed')], default='disconnected', max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary instance for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
                'verbose_name_plural': 'WhatsApp Sessions',
                'db_table': 'whatsapp_sessions',
                'indexes': [models.Index(fields=['user', 'status'], name='whatsapp_se_user_id_1b31d6_idx'), models.Index(fields=['user', 'is_primary'], name='whatsapp_se_user_id_488761_idx')],
                'unique_together': {('user', 'instance_name')},
            },
        ),
    ]
