# Generated by Django 5.0.14 on 2025-10-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='instance_name',
            field=models.CharField(default='Primary Instance', help_text='Friendly name for this WhatsApp instance', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary instance for this user'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappsession',
            unique_together={('user', 'instance_name')},
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['user', 'status'], name='whatsapp_se_user_id_1b31d6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['user', 'is_primary'], name='whatsapp_se_user_id_488761_idx'),
        ),
    ]
