# Generated by Django 5.0.14 on 2025-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'api_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('messages_sent', models.IntegerField(default=0)),
                ('api_requests', models.IntegerField(default=0)),
                ('media_sent', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Usage Statistics',
                'verbose_name_plural': 'Usage Statistics',
                'db_table': 'usage_stats',
                'ordering': ['-date'],
            },
        ),
    ]
