# Generated by Django 5.0.14 on 2025-10-04 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'api_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='api_logs_user_id_24cb6f_idx'), models.Index(fields=['-timestamp'], name='api_logs_timesta_dc0e61_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('messages_sent', models.IntegerField(default=0)),
                ('api_requests', models.IntegerField(default=0)),
                ('media_sent', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Statistics',
                'verbose_name_plural': 'Usage Statistics',
                'db_table': 'usage_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='usage_stats_user_id_49f752_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
