# Generated by Django 5.0.14 on 2025-10-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['user', '-timestamp'], name='api_logs_user_id_24cb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['-timestamp'], name='api_logs_timesta_dc0e61_idx'),
        ),
        migrations.AddIndex(
            model_name='usagestats',
            index=models.Index(fields=['user', '-date'], name='usage_stats_user_id_49f752_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagestats',
            unique_together={('user', 'date')},
        ),
    ]
