# Generated by Django 5.0.14 on 2025-10-05 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration date', null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikey',
            name='ip_whitelist',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses (optional)', null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'is_active'], name='api_keys_user_id_6e7352_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_key_291dcc_idx'),
        ),
    ]
